export const Access = {
  "user-management": ["Administrator", "Admin", "Director", "Manager", "Supervisor", "Client Supervisor"],
  "client-configuration": ["Administrator", "Admin"],
  "bucket-mapping": ["Administrator", "Admin", "Supervisor"],
  "global-insurance": ["Administrator", "Admin"],
  "global-mapping": ["Administrator", "Admin"],
  "dashboard": ["All"],
  "welcome-page": ["Client Supervisor"],
  "change-password": ["All"],
  "auto-allocation": ["Administrator", "Admin"],
  "client-instruction": ["Supervisor", "QC", "Client Supervisor"],
  "data-upload": ["Administrator", "Admin", "Supervisor"],
  "simple-report": ["Administrator", "Admin", "Director", "Manager", "Supervisor", "Controller"],
  "mis-report": ["Administrator", "Admin", "Director", "Manager", "Supervisor", "Controller"],
  "de-allocation": ["Supervisor"],
  "upload-file": ["Supervisor"],
  "view-file": ["Agent"],
  "agent": ["Agent"],
  "supervisor-agent": ["Supervisor"],
  "denial-code": ["Supervisor"],
  "supervisor-dashboard": ["Supervisor"],
  "standard-comment": ["Administrator", "Admin"],
  "client-assistance": ["QC", "Supervisor"],
  "client-approval": ["Client Supervisor"],
  "agent-correspondence": ["Agent"],
  "exception-entry": ["Client Supervisor"],
  "client-instruction-report": ["Client Supervisor"],
  "client-dashboard-report": ["Client Supervisor"],
  "client-user": ["Client User"],
  "tl-deny-report": ['Supervisor'],
  "ageing-dashboard-report": ["Supervisor", "Client Supervisor"],
  "bi-report": ["Supervisor", "Client Supervisor", "Client User"],
  // "kyi-report": ["Supervisor"],
  // "flash-dashboard": ["Supervisor"],
  // "payment-report": ["Supervisor"]
  "bcbs-data-upload": ["Supervisor"],
  "unworked-accounts-report": ["Administrator", "Admin", "Director", "Manager", "Supervisor", "Controller"],
  "production-report": ["Administrator", "Admin", "Director", "Manager", "Supervisor", "Controller"],
  "citra-audit": ["Supervisor"],
  "citra-audit-report": ["Administrator", "Admin", "Director", "Manager", "Supervisor", "Controller"],
  "citra-employee-mapping": ["Administrator", "Admin"],
  "agent-deallocation": "Supervisor",
  "productivity-report": ["Administrator", "Admin", "Director", "Manager", "Supervisor", "Client Supervisor"],
  "agent-productivity-report": ["Agent"],
  "client-user-mapping-management": ["Controller"],
  "user-menu-mapping": ["Administrator", "Admin"],
  /* concluder menus*/
  // "concluder-report": ["Supervisor", "Agent", "Admin"],
  // "deallocate-concluder": ["Supervisor", "Admin"],
  // "upload-mini-insurance": ["Supervisor", "Agent", "Admin"],
  "concluder-dashboard": ["Supervisor"],
  "pcn-report": ["Administrator", "Admin", "Director", "Manager", "Supervisor", "Controller"],
  "concluder-report": ["Supervisor", "Admin"],
  "concluder-deallocation": ["Supervisor"],
  "deallocate-module": ["Admin", "Supervisor"],
  "project-and-priority-report": ["Supervisor", "Admin"],
  "project-and-priority-dashboard": ["Supervisor", "Admin"],
  "client-simple-report": ["Client Supervisor"],
  "supervisor-inbox-mapping": ["Supervisor", "Admin"]
};
  //add new role here